version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    container_name: db-test
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - "./SQL/init.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - nt-test

  etl-python:
    container_name: etl-python
    build:
      context: .
      dockerfile: src/ingest/Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data:/data
    depends_on:
      database:
        condition: service_healthy
    networks:
      - nt-test
    
  output-python:
    container_name: output-python
    build:
      context: .
      dockerfile: src/output/Dockerfile
    environment:
      - PYTHONPATH=/app
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./data:/data
    networks:
      - nt-test
  
  admin:
    image: adminer
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - nt-test

volumes:
  output-python:
  etl-python:

networks:
  nt-test: